services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application-institution
    restart: on-failure
    ports:
      - '29790:29790'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9790
